"""Regression tests against a real Serum-generated VST3 state blob.

The fixture ``serum_2.1.4_default_state.bin`` is a state blob captured from
DawDreamer + Serum 2.1.4 immediately after the editor was opened and closed
without loading any preset. It contains no preset content — only Serum's
init-patch defaults. Its purpose is to lock in our codecs against
real-Serum-generated bytes so any drift in the JUCE-base64 alphabet, the
XferJson layout, or our hash-derivation understanding fails loudly.
"""
from __future__ import annotations

import hashlib
import struct
import xml.etree.ElementTree as ET
from pathlib import Path

import pytest

from serum2_preset_loader.wrappers import (
    JUCE_VST3_MAGIC,
    XFER_MAGIC,
    juce_memoryblock_b64decode,
    unwrap_xferjson,
)


FIXTURE = Path(__file__).parent / "fixtures" / "serum_2.1.4_default_state.bin"


@pytest.fixture(scope="module")
def state_blob() -> bytes:
    if not FIXTURE.exists():
        pytest.skip(f"fixture missing: {FIXTURE}")
    return FIXTURE.read_bytes()


def test_juce_envelope_decodes(state_blob):
    magic, xml_len = struct.unpack("<II", state_blob[:8])
    assert magic == JUCE_VST3_MAGIC
    xml = state_blob[8:8 + xml_len].decode("utf-8")
    root = ET.fromstring(xml)
    assert root.find("IComponent") is not None
    assert root.find("IEditController") is not None


def test_inner_xferjson_decodes(state_blob):
    magic, xml_len = struct.unpack("<II", state_blob[:8])
    xml = state_blob[8:8 + xml_len].decode("utf-8")
    icomp = juce_memoryblock_b64decode(ET.fromstring(xml).find("IComponent").text)
    meta, version, cbor = unwrap_xferjson(icomp)
    assert version == 2
    assert meta["component"] == "processor"
    assert meta["product"] == "Serum2"
    assert len(cbor) > 0


def test_metadata_hash_is_md5_of_compressed_cbor(state_blob):
    """Lock in the verified-from-real-state derivation: hash == md5(compressed_cbor).

    If this fails on a captured state from a future Serum build, the
    `_build_processor_metadata` derivation needs revisiting.
    """
    magic, xml_len = struct.unpack("<II", state_blob[:8])
    xml = state_blob[8:8 + xml_len].decode("utf-8")
    icomp = juce_memoryblock_b64decode(ET.fromstring(xml).find("IComponent").text)

    # Pull the compressed-CBOR bytes back out of the XferJson envelope.
    assert icomp[:9] == XFER_MAGIC
    json_len = struct.unpack("<Q", icomp[9:17])[0]
    after = icomp[17 + json_len:]
    compressed_cbor = after[8:]

    import json
    meta = json.loads(icomp[17:17 + json_len])
    assert meta["hash"] == hashlib.md5(compressed_cbor).hexdigest()


def test_juce_b64_round_trips_real_state_payload(state_blob):
    """Re-encoding the IComponent and decoding produces identical bytes.

    Catches alphabet/packing drift in the JUCE base64 codec against
    actually-Serum-shaped data, which is more thorough than synthetic
    bytes-of-range tests.
    """
    from serum2_preset_loader.wrappers import juce_memoryblock_b64encode

    magic, xml_len = struct.unpack("<II", state_blob[:8])
    xml = state_blob[8:8 + xml_len].decode("utf-8")
    original = juce_memoryblock_b64decode(ET.fromstring(xml).find("IComponent").text)
    re_encoded = juce_memoryblock_b64encode(original)
    assert juce_memoryblock_b64decode(re_encoded) == original
